services:
  tgfp-bot:
    image: johnofcamas/tgfp-job-runner
    container_name: tgfp-bot
    env_file:
      - stacks.env
    restart: unless-stopped
    volumes:
      - $TGFP_HOME/bot/scripts:/app/scripts
    depends_on:
      tgfp-mongodb-prd:
        condition: service_started
